name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Remote
        env:
          HG: ${{ secrets.HG }}
        run: |
          git remote add space https://$HG@github.com/Dineshkundo/hugging-face-demo.git

      - name: Push to Hub
        env:
          HG: ${{ secrets.HG }}
        run: |
          git push --force space main
